import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

import { TranslationContextProvider } from '@/contexts/TranslationContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <TranslationContextProvider>
      <html lang="pt-br">
        <body className={`${inter.className} bg-zinc-950`}>{children}</body>
      </html>
    </TranslationContextProvider>
  )
}
